spring.application.name=Proyecto_LogiTrackAO

spring.datasource.url=jdbc:mysql://localhost:3306/logitrack_db
spring.datasource.username=campus2023
spring.datasource.password=campus2023

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B59
jwt.expiration=86400000

# ERRORES
spring.web.resources.add-mappings=true